# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datareadout.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DataReadout(object):
    def setupUi(self, DataReadout):
        DataReadout.setObjectName(_fromUtf8("DataReadout"))
        DataReadout.resize(491, 215)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DataReadout.sizePolicy().hasHeightForWidth())
        DataReadout.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtGui.QHBoxLayout(DataReadout)
        self.horizontalLayout.setMargin(1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line_2 = QtGui.QFrame(DataReadout)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 0, 1, 6, 1)
        self.lbl_Counts = QtGui.QLabel(DataReadout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Counts.sizePolicy().hasHeightForWidth())
        self.lbl_Counts.setSizePolicy(sizePolicy)
        self.lbl_Counts.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_Counts.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.lbl_Counts.setFont(font)
        self.lbl_Counts.setIndent(0)
        self.lbl_Counts.setObjectName(_fromUtf8("lbl_Counts"))
        self.gridLayout.addWidget(self.lbl_Counts, 3, 0, 1, 1)
        self.lbl_FitVal = QtGui.QLabel(DataReadout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_FitVal.sizePolicy().hasHeightForWidth())
        self.lbl_FitVal.setSizePolicy(sizePolicy)
        self.lbl_FitVal.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_FitVal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.lbl_FitVal.setFont(font)
        self.lbl_FitVal.setObjectName(_fromUtf8("lbl_FitVal"))
        self.gridLayout.addWidget(self.lbl_FitVal, 3, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 4, 1, 1)
        self.lbl_chi = QtGui.QLabel(DataReadout)
        self.lbl_chi.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_chi.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.lbl_chi.setFont(font)
        self.lbl_chi.setIndent(0)
        self.lbl_chi.setObjectName(_fromUtf8("lbl_chi"))
        self.gridLayout.addWidget(self.lbl_chi, 1, 2, 1, 1)
        self.lbl_d = QtGui.QLabel(DataReadout)
        self.lbl_d.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_d.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.lbl_d.setFont(font)
        self.lbl_d.setIndent(0)
        self.lbl_d.setObjectName(_fromUtf8("lbl_d"))
        self.gridLayout.addWidget(self.lbl_d, 0, 2, 1, 1)
        self.lbl_I = QtGui.QLabel(DataReadout)
        self.lbl_I.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_I.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.lbl_I.setFont(font)
        self.lbl_I.setObjectName(_fromUtf8("lbl_I"))
        self.gridLayout.addWidget(self.lbl_I, 2, 0, 1, 1)
        self.lbl_twotheta = QtGui.QLabel(DataReadout)
        self.lbl_twotheta.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_twotheta.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.lbl_twotheta.setFont(font)
        self.lbl_twotheta.setIndent(0)
        self.lbl_twotheta.setObjectName(_fromUtf8("lbl_twotheta"))
        self.gridLayout.addWidget(self.lbl_twotheta, 2, 2, 1, 1)
        self.lbl_y = QtGui.QLabel(DataReadout)
        self.lbl_y.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_y.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.lbl_y.setFont(font)
        self.lbl_y.setLineWidth(1)
        self.lbl_y.setIndent(-1)
        self.lbl_y.setObjectName(_fromUtf8("lbl_y"))
        self.gridLayout.addWidget(self.lbl_y, 1, 0, 1, 1)
        self.lbl_x = QtGui.QLabel(DataReadout)
        self.lbl_x.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_x.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.lbl_x.setFont(font)
        self.lbl_x.setObjectName(_fromUtf8("lbl_x"))
        self.gridLayout.addWidget(self.lbl_x, 0, 0, 1, 1)
        self.line = QtGui.QFrame(DataReadout)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 3, 6, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lbl_min = QtGui.QLabel(DataReadout)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.lbl_min.setFont(font)
        self.lbl_min.setIndent(0)
        self.lbl_min.setObjectName(_fromUtf8("lbl_min"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_min)
        self.txtMin = QtGui.QLineEdit(DataReadout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtMin.sizePolicy().hasHeightForWidth())
        self.txtMin.setSizePolicy(sizePolicy)
        self.txtMin.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.txtMin.setFont(font)
        self.txtMin.setObjectName(_fromUtf8("txtMin"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtMin)
        self.gridLayout.addLayout(self.formLayout_2, 0, 4, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lbl_max = QtGui.QLabel(DataReadout)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.lbl_max.setFont(font)
        self.lbl_max.setIndent(0)
        self.lbl_max.setObjectName(_fromUtf8("lbl_max"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_max)
        self.txtMax = QtGui.QLineEdit(DataReadout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtMax.sizePolicy().hasHeightForWidth())
        self.txtMax.setSizePolicy(sizePolicy)
        self.txtMax.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.txtMax.setFont(font)
        self.txtMax.setObjectName(_fromUtf8("txtMax"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtMax)
        self.gridLayout.addLayout(self.formLayout, 1, 4, 1, 1)
        self.lbl_mean = QtGui.QLabel(DataReadout)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.lbl_mean.setFont(font)
        self.lbl_mean.setIndent(0)
        self.lbl_mean.setObjectName(_fromUtf8("lbl_mean"))
        self.gridLayout.addWidget(self.lbl_mean, 2, 4, 1, 1)
        self.btn_AutoScale = QtGui.QPushButton(DataReadout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_AutoScale.sizePolicy().hasHeightForWidth())
        self.btn_AutoScale.setSizePolicy(sizePolicy)
        self.btn_AutoScale.setObjectName(_fromUtf8("btn_AutoScale"))
        self.gridLayout.addWidget(self.btn_AutoScale, 0, 5, 2, 1)
        self.lbl_sigma = QtGui.QLabel(DataReadout)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.lbl_sigma.setFont(font)
        self.lbl_sigma.setObjectName(_fromUtf8("lbl_sigma"))
        self.gridLayout.addWidget(self.lbl_sigma, 3, 4, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(DataReadout)
        QtCore.QMetaObject.connectSlotsByName(DataReadout)

    def retranslateUi(self, DataReadout):
        DataReadout.setWindowTitle(_translate("DataReadout", "Form", None))
        self.lbl_Counts.setText(_translate("DataReadout", "Counts", None))
        self.lbl_FitVal.setText(_translate("DataReadout", "FitVal", None))
        self.lbl_chi.setText(_translate("DataReadout", "chi", None))
        self.lbl_d.setText(_translate("DataReadout", "d", None))
        self.lbl_I.setText(_translate("DataReadout", "I/E", None))
        self.lbl_twotheta.setText(_translate("DataReadout", "2θ", None))
        self.lbl_y.setText(_translate("DataReadout", "y", None))
        self.lbl_x.setText(_translate("DataReadout", "x", None))
        self.lbl_min.setText(_translate("DataReadout", "Min:", None))
        self.lbl_max.setText(_translate("DataReadout", "Max:", None))
        self.lbl_mean.setText(_translate("DataReadout", "mean", None))
        self.btn_AutoScale.setText(_translate("DataReadout", "Autoscale", None))
        self.lbl_sigma.setText(_translate("DataReadout", "sigma", None))

