# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datareadout.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DataReadout(object):
    def setupUi(self, DataReadout):
        DataReadout.setObjectName("DataReadout")
        DataReadout.resize(491, 215)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DataReadout.sizePolicy().hasHeightForWidth())
        DataReadout.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(DataReadout)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.line_2 = QtWidgets.QFrame(DataReadout)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 1, 6, 1)
        self.lbl_Counts = QtWidgets.QLabel(DataReadout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Counts.sizePolicy().hasHeightForWidth())
        self.lbl_Counts.setSizePolicy(sizePolicy)
        self.lbl_Counts.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_Counts.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.lbl_Counts.setFont(font)
        self.lbl_Counts.setIndent(0)
        self.lbl_Counts.setObjectName("lbl_Counts")
        self.gridLayout.addWidget(self.lbl_Counts, 3, 0, 1, 1)
        self.lbl_FitVal = QtWidgets.QLabel(DataReadout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_FitVal.sizePolicy().hasHeightForWidth())
        self.lbl_FitVal.setSizePolicy(sizePolicy)
        self.lbl_FitVal.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_FitVal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.lbl_FitVal.setFont(font)
        self.lbl_FitVal.setObjectName("lbl_FitVal")
        self.gridLayout.addWidget(self.lbl_FitVal, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 4, 1, 1)
        self.lbl_chi = QtWidgets.QLabel(DataReadout)
        self.lbl_chi.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_chi.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.lbl_chi.setFont(font)
        self.lbl_chi.setIndent(0)
        self.lbl_chi.setObjectName("lbl_chi")
        self.gridLayout.addWidget(self.lbl_chi, 1, 2, 1, 1)
        self.lbl_d = QtWidgets.QLabel(DataReadout)
        self.lbl_d.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_d.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.lbl_d.setFont(font)
        self.lbl_d.setIndent(0)
        self.lbl_d.setObjectName("lbl_d")
        self.gridLayout.addWidget(self.lbl_d, 0, 2, 1, 1)
        self.lbl_I = QtWidgets.QLabel(DataReadout)
        self.lbl_I.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_I.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.lbl_I.setFont(font)
        self.lbl_I.setObjectName("lbl_I")
        self.gridLayout.addWidget(self.lbl_I, 2, 0, 1, 1)
        self.lbl_twotheta = QtWidgets.QLabel(DataReadout)
        self.lbl_twotheta.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_twotheta.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.lbl_twotheta.setFont(font)
        self.lbl_twotheta.setIndent(0)
        self.lbl_twotheta.setObjectName("lbl_twotheta")
        self.gridLayout.addWidget(self.lbl_twotheta, 2, 2, 1, 1)
        self.lbl_y = QtWidgets.QLabel(DataReadout)
        self.lbl_y.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_y.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.lbl_y.setFont(font)
        self.lbl_y.setLineWidth(1)
        self.lbl_y.setIndent(-1)
        self.lbl_y.setObjectName("lbl_y")
        self.gridLayout.addWidget(self.lbl_y, 1, 0, 1, 1)
        self.lbl_x = QtWidgets.QLabel(DataReadout)
        self.lbl_x.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_x.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.lbl_x.setFont(font)
        self.lbl_x.setObjectName("lbl_x")
        self.gridLayout.addWidget(self.lbl_x, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(DataReadout)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 3, 6, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.lbl_min = QtWidgets.QLabel(DataReadout)
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.lbl_min.setFont(font)
        self.lbl_min.setIndent(0)
        self.lbl_min.setObjectName("lbl_min")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_min)
        self.txtMin = QtWidgets.QLineEdit(DataReadout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtMin.sizePolicy().hasHeightForWidth())
        self.txtMin.setSizePolicy(sizePolicy)
        self.txtMin.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.txtMin.setFont(font)
        self.txtMin.setObjectName("txtMin")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtMin)
        self.gridLayout.addLayout(self.formLayout_2, 0, 4, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lbl_max = QtWidgets.QLabel(DataReadout)
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.lbl_max.setFont(font)
        self.lbl_max.setIndent(0)
        self.lbl_max.setObjectName("lbl_max")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_max)
        self.txtMax = QtWidgets.QLineEdit(DataReadout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtMax.sizePolicy().hasHeightForWidth())
        self.txtMax.setSizePolicy(sizePolicy)
        self.txtMax.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.txtMax.setFont(font)
        self.txtMax.setObjectName("txtMax")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtMax)
        self.gridLayout.addLayout(self.formLayout, 1, 4, 1, 1)
        self.lbl_mean = QtWidgets.QLabel(DataReadout)
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.lbl_mean.setFont(font)
        self.lbl_mean.setIndent(0)
        self.lbl_mean.setObjectName("lbl_mean")
        self.gridLayout.addWidget(self.lbl_mean, 2, 4, 1, 1)
        self.btn_AutoScale = QtWidgets.QPushButton(DataReadout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_AutoScale.sizePolicy().hasHeightForWidth())
        self.btn_AutoScale.setSizePolicy(sizePolicy)
        self.btn_AutoScale.setObjectName("btn_AutoScale")
        self.gridLayout.addWidget(self.btn_AutoScale, 0, 5, 2, 1)
        self.lbl_sigma = QtWidgets.QLabel(DataReadout)
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.lbl_sigma.setFont(font)
        self.lbl_sigma.setObjectName("lbl_sigma")
        self.gridLayout.addWidget(self.lbl_sigma, 3, 4, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(DataReadout)
        QtCore.QMetaObject.connectSlotsByName(DataReadout)

    def retranslateUi(self, DataReadout):
        _translate = QtCore.QCoreApplication.translate
        DataReadout.setWindowTitle(_translate("DataReadout", "Form"))
        self.lbl_Counts.setText(_translate("DataReadout", "Counts"))
        self.lbl_FitVal.setText(_translate("DataReadout", "FitVal"))
        self.lbl_chi.setText(_translate("DataReadout", "chi"))
        self.lbl_d.setText(_translate("DataReadout", "d"))
        self.lbl_I.setText(_translate("DataReadout", "I/E"))
        self.lbl_twotheta.setText(_translate("DataReadout", "2θ"))
        self.lbl_y.setText(_translate("DataReadout", "y"))
        self.lbl_x.setText(_translate("DataReadout", "x"))
        self.lbl_min.setText(_translate("DataReadout", "Min:"))
        self.lbl_max.setText(_translate("DataReadout", "Max:"))
        self.lbl_mean.setText(_translate("DataReadout", "mean"))
        self.btn_AutoScale.setText(_translate("DataReadout", "Autoscale"))
        self.lbl_sigma.setText(_translate("DataReadout", "sigma"))

