# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multilauemainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MultiLaueMainWindow(object):
    def setupUi(self, MultiLaueMainWindow):
        MultiLaueMainWindow.setObjectName("MultiLaueMainWindow")
        MultiLaueMainWindow.resize(1100, 551)
        self.widgetMain = QtWidgets.QWidget(MultiLaueMainWindow)
        self.widgetMain.setObjectName("widgetMain")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetMain)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameImages = QtWidgets.QFrame(self.widgetMain)
        self.frameImages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameImages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameImages.setObjectName("frameImages")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameImages)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.frameImages)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widgetSumImage = QtWidgets.QWidget(self.splitter)
        self.widgetSumImage.setObjectName("widgetSumImage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widgetSumImage)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.layoutSumImage = QtWidgets.QVBoxLayout()
        self.layoutSumImage.setContentsMargins(11, 11, 11, 11)
        self.layoutSumImage.setSpacing(6)
        self.layoutSumImage.setObjectName("layoutSumImage")
        self.verticalLayout_3.addLayout(self.layoutSumImage)
        self.widgetTopograph = QtWidgets.QWidget(self.splitter)
        self.widgetTopograph.setObjectName("widgetTopograph")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widgetTopograph)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.layoutTopograph = QtWidgets.QVBoxLayout()
        self.layoutTopograph.setContentsMargins(11, 11, 11, 11)
        self.layoutTopograph.setSpacing(6)
        self.layoutTopograph.setObjectName("layoutTopograph")
        self.verticalLayout_4.addLayout(self.layoutTopograph)
        self.widgetSingleImage = QtWidgets.QWidget(self.splitter)
        self.widgetSingleImage.setObjectName("widgetSingleImage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widgetSingleImage)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.layoutSingleImage = QtWidgets.QVBoxLayout()
        self.layoutSingleImage.setContentsMargins(11, 11, 11, 11)
        self.layoutSingleImage.setSpacing(6)
        self.layoutSingleImage.setObjectName("layoutSingleImage")
        self.verticalLayout_5.addLayout(self.layoutSingleImage)
        self.horizontalLayout.addWidget(self.splitter)
        self.verticalLayout_2.addWidget(self.frameImages)
        MultiLaueMainWindow.setCentralWidget(self.widgetMain)
        self.menuBar = QtWidgets.QMenuBar(MultiLaueMainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1100, 22))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtWidgets.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuProcess = QtWidgets.QMenu(self.menuBar)
        self.menuProcess.setObjectName("menuProcess")
        MultiLaueMainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MultiLaueMainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MultiLaueMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MultiLaueMainWindow)
        self.statusBar.setObjectName("statusBar")
        MultiLaueMainWindow.setStatusBar(self.statusBar)
        self.action_Import_Scan = QtWidgets.QAction(MultiLaueMainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Import"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Import_Scan.setIcon(icon)
        self.action_Import_Scan.setObjectName("action_Import_Scan")
        self.action_Open_Scan = QtWidgets.QAction(MultiLaueMainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Open"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open_Scan.setIcon(icon1)
        self.action_Open_Scan.setObjectName("action_Open_Scan")
        self.actionProcess_MultiLaue = QtWidgets.QAction(MultiLaueMainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Compute"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProcess_MultiLaue.setIcon(icon2)
        self.actionProcess_MultiLaue.setObjectName("actionProcess_MultiLaue")
        self.actionSave_Aggregate_Image = QtWidgets.QAction(MultiLaueMainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Save Aggregate"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Aggregate_Image.setIcon(icon3)
        self.actionSave_Aggregate_Image.setObjectName("actionSave_Aggregate_Image")
        self.actionSave_Topograph_Image = QtWidgets.QAction(MultiLaueMainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Save Topograph"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Topograph_Image.setIcon(icon4)
        self.actionSave_Topograph_Image.setObjectName("actionSave_Topograph_Image")
        self.actionSave_Single_Image = QtWidgets.QAction(MultiLaueMainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Save Single"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Single_Image.setIcon(icon5)
        self.actionSave_Single_Image.setObjectName("actionSave_Single_Image")
        self.actionSave_All_Three_Images = QtWidgets.QAction(MultiLaueMainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Save"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_All_Three_Images.setIcon(icon6)
        self.actionSave_All_Three_Images.setObjectName("actionSave_All_Three_Images")
        self.actionClose = QtWidgets.QAction(MultiLaueMainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionOpen_GitHub_Website = QtWidgets.QAction(MultiLaueMainWindow)
        self.actionOpen_GitHub_Website.setObjectName("actionOpen_GitHub_Website")
        self.actionAbout_MultiLaue = QtWidgets.QAction(MultiLaueMainWindow)
        self.actionAbout_MultiLaue.setIconVisibleInMenu(True)
        self.actionAbout_MultiLaue.setObjectName("actionAbout_MultiLaue")
        self.actionPowder_Integrate = QtWidgets.QAction(MultiLaueMainWindow)
        self.actionPowder_Integrate.setObjectName("actionPowder_Integrate")
        self.menu_File.addAction(self.action_Open_Scan)
        self.menu_File.addAction(self.actionSave_Aggregate_Image)
        self.menu_File.addAction(self.actionSave_Topograph_Image)
        self.menu_File.addAction(self.actionSave_Single_Image)
        self.menu_File.addAction(self.actionSave_All_Three_Images)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Import_Scan)
        self.menu_File.addAction(self.actionProcess_MultiLaue)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionAbout_MultiLaue)
        self.menuHelp.addAction(self.actionOpen_GitHub_Website)
        self.menuProcess.addAction(self.actionPowder_Integrate)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuBar.addAction(self.menuProcess.menuAction())
        self.mainToolBar.addAction(self.action_Open_Scan)
        self.mainToolBar.addAction(self.actionSave_Aggregate_Image)
        self.mainToolBar.addAction(self.actionSave_Topograph_Image)
        self.mainToolBar.addAction(self.actionSave_Single_Image)
        self.mainToolBar.addAction(self.actionSave_All_Three_Images)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.action_Import_Scan)
        self.mainToolBar.addAction(self.actionProcess_MultiLaue)

        self.retranslateUi(MultiLaueMainWindow)
        QtCore.QMetaObject.connectSlotsByName(MultiLaueMainWindow)

    def retranslateUi(self, MultiLaueMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MultiLaueMainWindow.setWindowTitle(_translate("MultiLaueMainWindow", "MultiLaue"))
        self.menu_File.setTitle(_translate("MultiLaueMainWindow", "&File"))
        self.menuHelp.setTitle(_translate("MultiLaueMainWindow", "Help"))
        self.menuProcess.setTitle(_translate("MultiLaueMainWindow", "Process"))
        self.action_Import_Scan.setText(_translate("MultiLaueMainWindow", "&Import Scan"))
        self.action_Open_Scan.setText(_translate("MultiLaueMainWindow", "&Open Scan"))
        self.actionProcess_MultiLaue.setText(_translate("MultiLaueMainWindow", "Process &MultiLaue"))
        self.actionSave_Aggregate_Image.setText(_translate("MultiLaueMainWindow", "Save Aggregate Image"))
        self.actionSave_Topograph_Image.setText(_translate("MultiLaueMainWindow", "Save Topograph Image"))
        self.actionSave_Topograph_Image.setToolTip(_translate("MultiLaueMainWindow", "Save Topograph Image"))
        self.actionSave_Single_Image.setText(_translate("MultiLaueMainWindow", "Save Single Image"))
        self.actionSave_All_Three_Images.setText(_translate("MultiLaueMainWindow", "Save All Three Images"))
        self.actionClose.setText(_translate("MultiLaueMainWindow", "Close Scan"))
        self.actionOpen_GitHub_Website.setText(_translate("MultiLaueMainWindow", "Open GitHub Website"))
        self.actionAbout_MultiLaue.setText(_translate("MultiLaueMainWindow", "About MultiLaue"))
        self.actionPowder_Integrate.setText(_translate("MultiLaueMainWindow", "Powder Integrate"))

import icons_rc
